# Derived Dockerfile Example using `opm`
# https://github.com/openresty/docker-openresty
#
# Installs openresty-opm and then uses opm to install pgmoon.
#

FROM openresty/openresty:xenial

RUN opm get ledgetech/lua-resty-http
